### ISSUE TITLE
Specifying multiple run times did not work

### ISSUE THREAD

**Issue by chris-icart** [nickelser/zhong#37]
Using version 0.2.4 of the gem, I had this configuration:

```
every 1.day, 'call Foo', at: ['05:00', '08:00', '11:00'] do
  Foo.run( )            
end  
```
Foo.run( ) was only called at 5:00 am.

Do I need to change "every 1.day". to "every 1.hour" ?
Or is there a bug when using multiple times?

**Comment by reginaldojunior** [comment]
You fixed this or have is still problem?

**Comment by reginaldojunior** [comment]
@chris-icart how are you? 

I had same problem and fixed with work around separate block by time, see example

```
every 1.day, 'call Foo 1 ', at: ['05:00'] do
  Foo.run( )            
end  

every 1.day, 'call Foo 2', at: ['08:00'] do
  Foo.run( )            
end  

every 1.day, 'call Foo 3', at: ['11:00'] do
  Foo.run( )            
end  
```

I feel each block create one index in redis and not separate calls. Because this, you too need change the names blocks.

@nickelser you know about how to works register index redis, probably is each hour not registers in diferente index and because this happen the bug.

**Comment by chris-icart** [comment]
Hi @reginaldojunior , thanks for replying.  And I apologize for my late response.
Your solution definitely works.
I was able to get this working by doing this:

```
every 1.hour, 'call Foo', at: ['05:00', '08:00', '11:00'] do
  Foo.run( )            
end  
```
